### ISSUE TITLE
Does not compile with latest rust (1.0.0-alpha)

### ISSUE THREAD

**Issue by Kilobyte22** [arjantop/rust-bencode#30]
I just added this to my Cargo.toml. However on `cargo build` the compiler fails with this message (after numerous warnings):
```
src/bencode.rs:672:5: 672:86 error: method `emit_uint` is not a member of trait `serialize::Encoder`
src/bencode.rs:672     fn emit_uint(&mut self, v: uint) -> EncoderResult<()> { self.emit_i64(v as i64) }
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/bencode.rs:682:5: 682:84 error: method `emit_int` is not a member of trait `serialize::Encoder`
src/bencode.rs:682     fn emit_int(&mut self, v: int) -> EncoderResult<()> { self.emit_i64(v as i64) }
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/bencode.rs:988:5: 991:6 error: method `read_uint` is not a member of trait `serialize::Decoder`
src/bencode.rs:988     fn read_uint(&mut self) -> DecoderResult<uint> {
src/bencode.rs:989         dec_expect_value!(self);
src/bencode.rs:990         self.try_read("uint")
src/bencode.rs:991     }
src/bencode.rs:1013:5: 1016:6 error: method `read_int` is not a member of trait `serialize::Decoder`
src/bencode.rs:1013     fn read_int(&mut self) -> DecoderResult<int> {
src/bencode.rs:1014         dec_expect_value!(self);
src/bencode.rs:1015         self.try_read("int")
src/bencode.rs:1016     }
error: aborting due to 4 previous errors
Could not compile `bencode`.
```
Would be appreciated if you could figure that out :)

**Comment by arjantop** [comment]
I'm just updating the code right now.

**Comment by arjantop** [comment]
It should compile now but I did not manage to fix the tests yet but pushed the code anyway.

**Comment by Kilobyte22** [comment]
yes it does, lets hope it actually works :)

**Comment by arjantop** [comment]
The tests work now. Still quite a lot of work to get rid of all the warnings.

**Comment by flaub** [comment]
I didn't notice any warnings when building for beta.
